### ISSUE TITLE
can not set baudrate

### ISSUE THREAD

**Issue by XAndroider** [jpnurmi/flutter_libserialport#29]
when I set baudrate it does not work at all.

**Comment by katyo** [comment]
I have same issue when I attempt to set `SerialPortConfig` on Linux:

```dart
port.config.baudRate = 9600;
```

```
No such file or directory, errno = 2

When the exception was thrown, this was the stack:
#0      Util.call (package:libserialport/src/util.dart:39:7)
#1      _SerialPortImpl.config (package:libserialport/src/port.dart:335:12)
...
```

```dart
var config = SerialPortConfig();
config.baudRate = 9600;
port.config = config;
```

```
No such file or directory, errno = 2

When the exception was thrown, this was the stack:
#0      Util.call (package:libserialport/src/util.dart:39:7)
#1      _SerialPortImpl.config= (package:libserialport/src/port.dart:347:10)
...
```

**Comment by mortenboye** [comment]
Thanks @katyo for sharing that discovery. Setting the config after opening the port, solve my issue also. Great!

**Comment by usernema01** [comment]
> 当我尝试`SerialPortConfig`在 Linux 上设置时，我遇到了同样的问题：
> 
> ```dart
> port.config.baudRate = 9600;
> ```
> 
> ```
> No such file or directory, errno = 2
> 
> When the exception was thrown, this was the stack:
> #0      Util.call (package:libserialport/src/util.dart:39:7)
> #1      _SerialPortImpl.config (package:libserialport/src/port.dart:335:12)
> ...
> ```
> 
> ```dart
> var config = SerialPortConfig();
> config.baudRate = 9600;
> port.config = config;
> ```
> 
> ```
> No such file or directory, errno = 2
> 
> When the exception was thrown, this was the stack:
> #0      Util.call (package:libserialport/src/util.dart:39:7)
> #1      _SerialPortImpl.config= (package:libserialport/src/port.dart:347:10)
> ...
> ```
> 
> UPD：正如我在`libserialport`示例中看到的，似乎应该在打开端口后设置配置。

thank you baby! I solve it! 太屌了

**Comment by VinayakaKS** [comment]
Hi, I may be late to answer to this, but thinking it will help others who end up at this problem.
The port.config needs to be set only after opening the port.

      SerialPort port = SerialPort(availablePorts[widget.comPort]);

      final portconfig = SerialPortConfig();
      portconfig.baudRate = 115200;
      
      SerialPortReader reader = SerialPortReader(port, timeout: 10000);
     
      port.openReadWrite();
      port.config = portconfig;

**Comment by lucafabbri** [comment]
Thanks @VinayakaKS I'll check it further to avoid issues when config is set before opening

**Comment by dropik** [comment]
That's weird, but it indeed works if setting config takes place after .openReadWrite(), not before.

**Comment by M0JXD** [comment]
I've spent an hour trying to debug this issue (and many days wondering why the port behaviour has been so inconsistent) just to find out the the config must be set after opening the port (which is backwards to what would be expected).

Could opening the port please be added to the example and possibly documented clearly somewhere? It seems many users have been troubled by this, and it's the root cause of many open issues both in this repo and the underlying [FFI repo](https://github.com/jpnurmi/libserialport.dart), e.g. [this one](https://github.com/jpnurmi/libserialport.dart/issues/24).

[The documentation stresses the importance of setting the config](https://pub.dev/documentation/flutter_libserialport/latest/flutter_libserialport/SerialPortConfig-class.html) but the example in FFI repo README doesn't at all.
