### ISSUE TITLE
errno = 2 in Android devices

### ISSUE THREAD

**Issue by hargoyal** [jpnurmi/flutter_libserialport#38]
I am getting below error while running flutter app in Android. Same project run in Windows desktop fluently.
I have tested on Android 5, 10 & 11, getting same issue.
I also tested by varying **flutter_libserialport** versions{from:0.2.0 - to:0.2.3}

What will be the reason behind this issue ?

======== Exception caught by widgets library ================
The following SerialPortError was thrown building Builder:
No such file or directory, errno = 2

The relevant error-causing widget was: 
  Directionality Directionality:file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.3.8/lib/get_navigation/src/root/get_material_app.dart:217:12
When the exception was thrown, this was the stack: 
#0      Util.call (package:libserialport/src/util.dart:39:7)
#1      _SerialPortImpl._init (package:libserialport/src/port.dart:221:10)
#2      new _SerialPortImpl (package:libserialport/src/port.dart:211:42)
#3      new SerialPort (package:libserialport/src/port.dart:72:38)
#4      new _HomeState (package:usb_serial_sample/ui/main.dart:51:23)
#5      Home.createState (package:usb_serial_sample/ui/main.dart:27:31)
#6      new StatefulElement (package:flutter/src/widgets/framework.dart:4677:25)
#7      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:737:38)
...     Normal element mounting (169 frames)
#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#177    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#178    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (396 frames)
#574    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#575    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#576    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#577    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#578    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#579    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#580    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#581    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#582    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

**Comment by lucafabbri** [comment]
@hargoyal this might be related to 
#76
